### ISSUE TITLE
NY13 map shimmy

### ISSUE THREAD

**Issue by jfbratt** [mapping-elections/site#42]
The NY map shimmies.

**Comment by lmullen** [comment]
That typically happens when it's having a hard time deciding exactly how to fit the zoom to the canvas. Try increasing the height by 25 px or so.

**Comment by jfbratt** [comment]
Increasing the height from 700 to 725 fixes the shimmy. I just checked the previous maps for NY and they are all shimmying so I will need to go back and adjust the height on all of them.
