### ISSUE TITLE
Re-check map text for these elections

### ISSUE THREAD

**Issue by jfbratt** [mapping-elections/site#57]
- [x] GA9
- [ ] GA10
- [x] NJ11

Why does it say "Mapping this election is incomplete because of the lack of local returns in many areas" when they are missing, at most, 4 counties?

**Comment by gswain2** [comment]
I think somethings is wrong with the data for GA10. The map text and table list the four elected candidates as "Federalists" even though they show up on the map in the Dem-Rep purple color and are listed as Dem-Rep on CongBio and in the following GA 11th Congress. Could you check the data and see what is going on? When you are finished, I will update the map text accordingly.

**Comment by jfbratt** [comment]
The map data is correct. Can you please change the text from "Federalists" to "Democratic-Republicans"? I changed the .csv file for the table and will regenerate the .md file after you update the map text.

**Comment by jfbratt** [comment]
@gswain2 I updated the map text and the table.
