### ISSUE TITLE
Text flow on front page

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/site#6]
On certain screen sizes (e.g. iPad Air 2 in portrait mode, though you can reproduce this on any browser at the right width) text gets trapped to the right of the image of the blog post on the front page. So "the" is orphaned to the right while the other text flows below it.

This is not a problem on the blog page, but on the blog page the post title goes below the image (which makes sense to me) and on the home page the post title goes above the image for small screen widths.

**Comment by kalbers** [comment]
Good catch on this. It just requires an additional class on the post itself. I'll include it in the documentation.
