### ISSUE TITLE
NH12 Required 2 general elections

### ISSUE THREAD

**Issue by jfbratt** [mapping-elections/site#60]
New Hampshire law required a majority to elect for the U.S. House of Representatives. A 2nd Trial would be held in 1811. The MEAE page only reflects that first election in the map, the candidate tables, and the NNV links.

What is our policy in handling multiple ballot At-large elections?

**Comment by lmullen** [comment]
Which one best represents the electorate? If the first one shows considerably more variation in who was voted for, then we should keep it instead of the second trial. But otherwise keep the one that decides the election.

**Comment by jfbratt** [comment]
The first general election elected 2  reps while the 2nd ballot/general election elected 3 reps. 
[https://elections.lib.tufts.edu/catalog/tufts:nh.uscongress.1810](https://elections.lib.tufts.edu/catalog/tufts:nh.uscongress.1810)
[https://elections.lib.tufts.edu/catalog/tufts:nh.uscongress.2.1811](https://elections.lib.tufts.edu/catalog/tufts:nh.uscongress.2.1811)

**Comment by lmullen** [comment]
Let me think about this one when I get to reviewing the 12th Congress. Adding the label for the Congress to this one so I don't miss it.

**Comment by jfbratt** [comment]
Map text: Change to articulate who was elected on second ballot and explain percentages (people cast multiple votes)

**Comment by jfbratt** [comment]
@lmullen I left the map data showing the first general election and then changed the map text to this:

> New Hampshire used a statewide at-large method for electing members to Congress. New Hampshire law required a majority to elect for the U.S. House of Representatives. Each voter was allotted five votes for the five seats. The percentages reflect the percent of the total votes cast. The first ballot resulted in only two representatives elected. Therefore, a [second ballot](https://elections.lib.tufts.edu/catalog/tufts:nh.uscongress.2.1811) was held to elect John A. Harper, Obed Hall, and George Sullivan.
