### ISSUE TITLE
KY 17 - District 5 missing in chart, special election district 7

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#64]
-District 5 is not in the table. It looks like we have a result for that election (even if we don't have vote totals).
-District 7 Special Election vs. general:
This election has two special elections listed for districts 7 and 8. District 8 appears on the maps page as I would it expect it: Wingfield Bullock (the one originally elected) is shown in the table, the votes for his election are shown on the map, and NNV link at the bottom goes to the election Bullock wins. Then we have included a link in the map text that goes to NNV about the special election to find his replacement. District 7 is not like this. Instead, of showing the original 1820 election (where George C. Robinson is elected)  our table, map and NNV link all show the results of the 1821 special election when John Speed Smith is elected to take Robinson's place. The results of 1820 election are found here: https://elections.lib.tufts.edu/catalog/tufts:ky.uscongress7.1820 while the results for the special election we are using (1821) is here: https://elections.lib.tufts.edu/catalog/tufts:ky.uscongress7.1821

**Comment by lmullen** [comment]
Problematic table from @jfbratt. @lmullen will investigate.

![screen shot 2018-09-10 at 1 22 24 pm](https://user-images.githubusercontent.com/183672/45323062-07d45a80-b518-11e8-91ec-4cd0753b1a73.png)

**Comment by lmullen** [comment]
Fixed.
