### ISSUE TITLE
MA 16 - ME 17 as related map?

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#67]
On the ME 17 Congress page, we added a link to the "Related Maps" section for the "previous" map to go to MA 16. Should this be done in reverse for the MA 16 page? In other words, should the "Related Maps" for MA 16 have links to MA 15, MA 17 and ME 17? 
(There are some interesting links between MA 16 and ME 17. For example, there is a special election I moved from the ME 17 page to the MA 16 page, as it applies to the 16th Congress, not the 17th. The seat is originally for MA District 14. But, by the time the special election takes place in November 1820 to replace the candidate who had resigned, that seat/district become part of the state of Maine and is listed under Maine's elections on NNV.)

**Comment by lmullen** [comment]
Done.
