### ISSUE TITLE
ME19 Democratic-Republican vs. Adams/Clay

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#68]
Just to clarify, where are we getting the candidates' party affiliation from? NNV only or a combo of NNV and CongBio? 
For example, our ME19 map text says that ME elected 7 Dem-Rep., one of which was Adams-Clay. We list David Kidder as the only Adams/Clay candidate that was elected. 
If we are relying only on NNV, then it doesn't list any candidates as Adams/Clay. 
But is we are consulting CongBio, then five of the elected candidates (Burleigh, Herrick, Lincoln, O’Brien and Kidder) are listed as Adams candidates for the 19th Congress in CongBio.

**Comment by lmullen** [comment]
@gswain2 The party affiliations come in the first instance from NNV, then are corrected and filled in by Congressional Bio and other sources as necessary. NNV is very uneven in its coverage of party affiliations, and we have had to make our own categories to make the mapping manageable.

@jfbratt Can you and @gswain2 please resolve what the party affiliations should be for this map and adjust the candidates and parties data as necessary?

**Comment by jfbratt** [comment]
Updated candidates to Adams/Clay.
