### ISSUE TITLE
MD 12-14 Table Percentages

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#69]
The percents in the tables for MD 12-14th look strange—many over 100%. For example, John Brown has 199.4% of the vote in MD's 12th Congress, District 7. If there is a unusual situation that causes the percentages reported to be equal more than 100%, we should mention that in the map text.

**Comment by lmullen** [comment]
@jfbratt Can you confirm that nothing is wrong with the data? If the data is fine, I will look to see where we are calculating the percentages wrong.

**Comment by jfbratt** [comment]
@lmullen The data is correct. It looks like the percentages and raw vote counts are being doubled on the table. I will check the .Rmd file.

**Comment by lmullen** [comment]
I didn't see any percentages over 100, including in the John Brown example above. I think this was caused by a bug that I fixed elsewhere and that the site was generated with older code when this issue was created.
