### ISSUE TITLE
MA 18/19 Dem-Rep vs. Adams/Clay, Jacksonian, etc.

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#70]
This is similar to issue #68.  
For example, in MA's 18th Congress, we have listed Jonas Sibley as an Adams/Clay candidate, have used a legend that includes Adams/Clay as a separate color, and have map text to indicate that he is the only Adams/Clay candidate. 
We have two options: 1) Change Sibley to a general "Dem-Rep" in the 18th and change the legend for the 18th to "fed-vs-rep" 2) If we are going to be specific about one candidate, then we should be specific about all of them, and update their party affiliations in both the 18th and 19th Congresses, and update the legend for the 19th to "congress-18-19"

**Comment by jfbratt** [comment]
@lmullen @gswain2 I think the larger question is "In elections in the 18th and 19th congresses where we rely on CongBio for a party affiliation, should we then change the affiliation for each other election in that state (particularly if they are Adams/Clay or Jacksonian)?" I think there is a compelling argument that we need to be consistent in how we organize party affiliations, especially when it concerns factions.

**Comment by gswain2** [comment]
The party affiliations that need to be updated are listed below. They are also listed in the "MA 18/19 Parties" spreadsheet sent via Slack, under the columns "18th MEAM (Should Be)" and "19th MEAM (Should Be)." The updates that are needed are highlighted in blue.
2 | Benjamin W. Crowninshield - Adams/Clay 18th, Adams/Clay 19th
3 | Jeremiah Nelson - Adams/Clay 18th
4 | Timothy Fuller - Adams/Clay 18th
6 | John Locke - Adams/Clay 18th, Adams/Clay 19th
7 | Samuel C. Allen - Adams/Clay 18th, Adams/Clay 19th
8 | Samuel L. Lathrop - Adams/Clay 18th, Adams/Clay 19th
9 | Henry W. Dwight - Adams/Clay 18th, Adams/Clay 19th
10 | John Bailey - Adams/Clay 19th
11 | Aaron Hobart - Adams/Clay 18th, Adams/Clay 19th
12 | Francis Bayliss - Jacksonian 18th, Jacksonian 19th
13 | John Read - Adams/Clay 18th, Adams/Clay 19th

**Comment by jfbratt** [comment]
MA18
- [x] 2 | Benjamin W. Crowninshield - Adams/Clay
- [x] 3 | Jeremiah Nelson - Adams/Clay
- [x] 4 | Timothy Fuller - Adams/Clay 
- [x] 6 | John Locke - Adams/Clay
- [x] 7 | Samuel C. Allen - Adams/Clay
- [x] 8 | Samuel L. Lathrop - Adams/Clay
- [x] 9 | Henry W. Dwight - Adams/Clay
- [x] 11 | Aaron Hobart - Adams/Clay
- [x] 12 | Francis Bayliss - Jacksonian
- [x] 13 | John Read - Adams/Clay

MA19
- [x] 2 | Benjamin W. Crowninshield - Adams/Clay 
- [x] 6 | John Locke - Adams/Clay
- [x] 7 | Samuel C. Allen - Adams/Clay
- [x] 8 | Samuel L. Lathrop - Adams/Clay
- [x] 9 | Henry W. Dwight - Adams/Clay
- [x] 10 | John Bailey - Adams/Clay 
- [x] 11 | Aaron Hobart - Adams/Clay 
- [x] 12 | Francis Bayliss - Jacksonian
- [x] 13 | John Read - Adams/Clay

**Comment by jfbratt** [comment]
@gswain2 If you could record the candidates who need their party affiliation updated like this, it would be easier for me to keep track of what I have/have not done. Thanks.

**Comment by jfbratt** [comment]
Updated both MA18 and MA19.
