### ISSUE TITLE
NY 14th, District 12 - Replace Special Election Data with General

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#72]
In district 12, we seem to be using data from a special election (https://elections.lib.tufts.edu/catalog/tufts:ny.uscongress12.special.1815) instead of the original/general election data (https://elections.lib.tufts.edu/catalog/tufts:ny.uscongress12.1814). I think we need to redo the table and map to reflect the original election, in which two candidates (Savage and Pond) were elected (regardless of the the fact that Pond died before he could take his seat.)

**Comment by lmullen** [comment]
@jfbratt Is this an example of one where we compiled the list of elections before we had a clear principle for whether to use general or specific?

**Comment by jfbratt** [comment]
Yeah, I think this was a lingering error from before we defined "elected."
