### ISSUE TITLE
PA 11th-16th, District 11 (then 15) - Venango & Warren County Votes

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#77]
In the PA 11th-16th Congresses, the votes for Venango & Warren county are combined. We are not consistent about how we display this. 

In the 11th, 12th, 14th and 15th Congresses, we show the combined vote totals/percentages only in Venango County on the maps, and Warren County is left blank. In the 13th Congress, we show the combined vote totals/percentages in Venango County and the combined percentages (but not vote totals) in Warren. In the 16th Congress, both counties show up blank. We have map text ("The votes cast in Warren County are included in the Venango County totals.") to explain this only for the 15th Congress (but not for the 11th-14th, and 16th). 

Cong. | Dist. | Venango Map | Warren  Map | Text
--- | --- | ---  | --- | --- 
11 | 11 | V/P | - | -
12 | 11 | V/P | - | - 
13 | 15 | V/P | P | - 
14 | 15 | V/P | - | - 
15 | 15 | V/P | - | Yes 
16 | 15 | - | - | -

V/P = Showing vote totals and party percentages, P = showing party percents only

When vote totals have been combined in two counties for other states (Ex. Sandusky and Seneca counties in Ohio), we have added text to the popup (Ex. "County-level returns are not available for this county, so party percentages for the district as a whole have been displayed."), and just displayed the party level percentages instead of the vote totals. Both counties have color, and display the same party percentages. Do we want to mirror that method with Venango & Warren counties in PA?

**Comment by jfbratt** [comment]
@gswain2 @lmullen My 2 cents would be to include the total votes and percentages in one county, leave the other county completely blank, and then detail that in the map text. This allows us to display the data NNV has for that area and gives a better picture of that region, I think, than displaying the district party percentages.

**Comment by jfbratt** [comment]
I updated the data for both PA13 and PA16 to be consistent with the other congresses. I also updated OH18 to be consistent. 

@gswain2 Can you update the map text for these elections and for OH18 to note the peculiar reporting?

**Comment by gswain2** [comment]
- [X] Updated map text for PA11, PA12, PA13, PA14, PA16. 
- [X] The text for OH18 was already correct. 
- [x] OH18 pop-up problem 
We are still getting the popup in Sandusky County that says "County-level returns are not available for this county, so party percentages for the district as a whole have been displayed." This first part of this is correct (county level returns for ONLY Sandusky are not available), but the second part is wrong (we can't say that we are using party percentages for the district when we are using party percentages based on the combined vote totals). I vote that we scrap the extra pop-up text and just let the map text (Sandusky and Seneca counties were reported as one unit...) explain this unusual situation.

**Comment by jfbratt** [comment]
Updated the .csv file and push the updated .md file.
