### ISSUE TITLE
Missing Seats

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#78]
- [x] PA 18
Dist. 11 - (plural district, with two seats) - Add James Wilson as elected = TRUE, add link to Wilson's CongBio profile (http://bioguide.congress.gov/scripts/biodisplay.pl?index=W000588)

- [x] PA 19
Dist. 2 - Joseph Hemphill, Elected
Dist. 3 - Daniel H. Miller, Elected 
Dist. 16 - Walter Forward - remove the checkmark, not elected

**Comment by jfbratt** [comment]
NNV has Wilson's two elections split into 2 different candidate IDs. I copied the CongBio data over to the second id in our candidates.csv and rebuilt the markdown page. Also, I changed the map text to reflect the added 11 district which elects 2 candidates.
