### ISSUE TITLE
TN 11th - NNV data error results in flipped district numbers

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#79]
Sometimes TN used district names and sometimes they used numbers. In general, this is the way they correspond: 

Number | Name | 3 Counties
--- | --- | ---
1 | Washington | Carter, Washington, Hawkins
2 | Hamilton | Anderson, Campbell, Knox
3 | Mero | Bedford, Davidson, Wilson

In the 11th Congress, the NNV data is wrong. It says that Weakley was elected for the Hamilton District (2), but all of the counties listed (Bedford, Davidson, etc.) are from Mero. Conversely, it says that Miller was elected from the Mero District (3), but then lists votes from Knox County (which is in the Hamilton District). This error is made on the typed up "page image" section, but if you read the handwritten notes below that, Miller is correctly listed as being elected from the Hamilton District. 

This error in the NNV data has caused us to incorrectly report the districts Weakley and Miller were elected from. The map (since it is done by county) seems to be unaffected.

To fix:
- [ ] In data for meae.congressional.congress11.tn.county: change candidates "Weakley," "Maury," "Lyon" and "Fisk" to "election_id" = "tn.congress.mero.1809" and "district" =  "3"
- [ ] In data for meae.congressional.congress11.tn.county: change candidates "Miller" and "scattering" to "election_id" = "tn.congress.hamilton.1809" and "district" =  "2"
- [x] On map page, in the NNV Data links at the bottom: change "District 2" to link to https://elections.lib.tufts.edu/catalog/tufts:tn.congress.mero.1809 and "District 3" to link to https://elections.lib.tufts.edu/catalog/tufts:tn.congress.hamilton.1809

**Comment by jfbratt** [comment]
We identified this error in #37 . Thanks for mapping out what is happening and what should be done to rectify the error. I updated the data and the election .Rmd file. Should be all good to go.
