### ISSUE TITLE
MA text issue (from Zagarri)

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/site#81]
> You probably are aware of this already, but almost all of the Massachusetts maps have some sort of extra text at the top of the space--looks code or something. Just needs to be removed.

@jfbratt Could you please look into this?

**Comment by jfbratt** [comment]
The warning message is coming from the data-manipulation.R script, join_to_spatial function, line 179. Its coming from the section parsing out Maine and Massachusetts. I haven't figured out why it is being generated.

**Comment by lmullen** [comment]
I'll take a look too. Good to know where I should start.

**Comment by lmullen** [comment]
Fixed in the mappingelections package.
