### ISSUE TITLE
PA Counties Counted Together

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#87]
In PA, counties are often officially formed, but do not have their own separate elections until they gain enough population. Therefore, in many cases, vote totals for one or more newly formed counties are included/reported with a nearby county. We have not been consistent about we treat these in the maps and map text. 

An example of one way we have attempted to show this: PA 11
Votes for Venango and Warren Counties were reported together. On the map, we showed the vote totals and party percentages in Venango, but left Warren blank. We added map text to tell the reader that they were reported together. 

Nevertheless, there are other counties (notably Potter, Mckean, Clearfield, and Tioga Counties) that are mentioned in the NNV footnotes as typically being combined/reported with other counties, but we have not mentioned them. We show them as blank/no data. There are instances of this in the 10th-18th PA Congresses. 

There also seems to be something wrong with the district lines in Northern PA in relation to Potter and McKean Counties. 
Ex. PA18: Our map draws a dark line between these two counties, indicating that they are in separate districts. But the pop-ups correctly identify them as both belonging to District 9. [1822 District 9](https://elections.lib.tufts.edu/catalog/12579t447) gives one total for all three counties. This is not surprising because Potter and McKean Counties were formed out of Lycoming County in 1804, and all three voted together until 1814. After 1814, Lycoming voted alone, but Potter and McKean Counties voted together. Finally in 1824, all three counties started having separate elections. [According to [footnote 8](https://elections.lib.tufts.edu/catalog/41687j98t).]

How to fix: 
The easiest (although most wordy) solution would be add a sentence to the map text for each set of combined counties. "The votes cast in Warren County are included in the Venango County totals. The votes cast in Clearfield County are included in the Centre County totals....etc."

Another solution (which we have done before and I might prefer) is to sort of treat the counties being reported together as one large political (county) unit.  We have colored in both counties based on the party percentages from the combined votes, and shown the PP and Vote totals in one (normally the larger/older) county and only PP in the other (as to not duplicate votes). This is more visually appealing (less blank counties) and helps viewer at a glance difference between counties for which we have no data whatsoever and counties for which we do have data. It also helps keep map text to a minimum.

**Comment by lmullen** [comment]
@gswain2 Can you please make the changes in line with your second proposal? 

These changes need to be made in `congressional-counties-parties.csv` in the `elections-data` repository.

**Comment by gswain2** [comment]
I updated the map text and `congressional-counties-parties.csv` to reflect these changes.
